quarkus:
  datasource:
    db-kind: postgresql 
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/QuarkusBook
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8090
# Swagger: http://localhost:8090/q/swagger-ui/