quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/QuarkusBook
  hibernate-orm:
    database:
      generation: update
